Hyperspace world: Hyperspace
Hyperspace travel warmup: 60
Hyperspace travel speed: 300.0
Beacon range: 200
Hyperspace enter sound: ENTITY_ENDERMAN_TELEPORT
Hyperspace exit sound: ENTITY_ENDERMAN_TELEPORT
Hyperspace charge sound: BLOCK_STONE_BREAK
Max hyperdrives on craft:
  Starfighter: 1
  Starship: 2
Allowed craft types for hyperspace sign:
  - Starfighter
  - Starship
Allowed craft types for jump command:
  - Starfighter
  - Starship
Hypermatter:
  type: EMERALD
#
#
#
