Hyperspace world: Hyperspace
Hypermatter: EMERALD
Hyperspace travel warmup: 60
Hyperspace travel speed: 300.0
Beacon range: 200
Hyperspace enter sound: ENTITY_ENDERMAN_TELEPORT
Hyperspace exit sound: ENTITY_ENDERMAN_TELEPORT
Hyperspace charge sound: BLOCK_STONE_BREAK
#
#
#
Per craft type settings:
  CraftTypeName:
    Hypermatter: EMERALD
    Hyperspace travel warmup: 60
    Hyperspace travel speed: 300.0